### ISSUE TITLE
Transparent png files create dots in upper left corner

### ISSUE THREAD

**Issue by Tohoff** [mindsharestudios/mthumb#10]
When resizing Transparent PNG-files, a little black dot is created in the upper left corner of the image which is not transparent.

See the rotator images at:
https://dethleffs.campingoase-kerpen.de/

**Comment by Tohoff** [comment]
Addition: it only happens when sharpening the images after resizing (s=1).

**Comment by attackant** [comment]
Do not use the sharpen filter in that case.
