### ISSUE TITLE
localhost:3000 seen as an external site

### ISSUE THREAD

**Issue by markbloomfield** [mindsharestudios/mthumb#7]
Small issue, but when developing on a local URL with a port, the site is seen as external and thus all I get is the 'no hotlinking' script

I imagine this is just something that needs to be changed in the conditional on line 456 ?

![window-2](https://cloud.githubusercontent.com/assets/936966/8473048/a3e4d404-20a6-11e5-9a40-d336e7ac3867.jpg)

**Comment by attackant** [comment]
Oddly, I can't duplicate this bug. I'm wondering if this could have something to do with the referral string and not the port. Do you have any other ideas?

![screenshot from 2015-07-07 11 03 27](https://cloud.githubusercontent.com/assets/4309872/8552070/daab348e-2497-11e5-919f-d062b9c7f4c9.png)

**Comment by markbloomfield** [comment]
Sorry for delay on my reply... I use gulp/npm for css processing etc. So the URL I dev on uses that port cos of the way browsersync works.

Definitely doesn't work when using that method (https://github.com/jono99) . Just setup a friend with the same base theme and he experiences the same problem. 

For what it's worth, the basetheme I use is here: https://github.com/markbloomfield/BaseTheme.

**Comment by jono99** [comment]
![image](https://cloud.githubusercontent.com/assets/4537665/9380202/efaf6e86-472e-11e5-825e-731b5dd4558e.png)

Here is a comparison in the markup. Left side is working fine, even with port :8005 in the url. Right side is using gulp on port :3000. Gulp seems to be including the '//localhost:3000' in the url

**Comment by attackant** [comment]
Thanks for the follow up. This seems like an edge case so I'm not going to prioritize a fix right now but if you can troubleshoot it and submit a pull request I'd be happy to merge your code.

**Comment by markbloomfield** [comment]
Fair enough @attackant. Did a bit of playing around, and basically just remove //localhost:3000 from the generated URL's with a `str_replace()` for `$_SERVER['SERVER_NAME']`

Thanks for your attention anyways :)

**Comment by markbloomfield** [comment]
Just to clarify, it wasn't actually a change required in your script. WordPress' `get_bloginfo('template_directory')` function returns the URL with the port etc in it, which I ran through str_replace() to fix the problem I was having. 

As you were... :)

**Comment by attackant** [comment]
Thanks! Is this worth adding to the our code? Or is this just specific to your setup?

**Comment by markbloomfield** [comment]
I think it's mostly on 'our' side. Using the following function now in all my sites:

    /*----------  Fetch Thumbnail + Resize etc  ----------*/
    function fetch_thumbnail($id, $w, $h) {
        // get the post thumbnail
        $thumbnail = wp_get_attachment_image_src( get_post_thumbnail_id($post->ID), full );
        // clean up $thumbnail
        $thumbnail = str_replace('http://'.$_SERVER['SERVER_NAME'], '', $thumbnail[0]);

        // return the image URL
        return str_replace('http://'.$_SERVER['SERVER_NAME'], '', get_bloginfo('template_directory')).'/mthumb.php?src='.$thumbnail.'&w='.$w.'&h='.$h;
    }

Then usage is

`<img src="<?php echo fetch_thumbnail($post->ID, 500, 180); ?>">`
